### ISSUE TITLE
Why this app isn't working anymore?

### ISSUE THREAD

**Issue by RupomChowdhury** [Programming-Hero1/neptune-desktop-app#2]
Hello @anwarpro & @MuktadirHassan ,

Can't even watch any video including those which are already watched before.
I can watch those video from web browser but not from this desktop app.
It's showing "Unit Link Not Found".

Thanks

**Comment by MuktadirHassan** [comment]
Desktop app has a different server than the web app. So, it's possible that the video is not uploaded to the desktop backend server yet. If the issue persists, please post on your respective facebook group about the issue.
